SampleApp/config/routes.rb
Rails.application.routes.draw do
 
  

  root              'static_pages#home'
  
  get 'help'  =>    'static_pages#help'
  get 'about' =>    'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  
  get 'signup' =>   'users#new'

  resources :users
  

end

SampleApp/app/models/user.rb
class User < ActiveRecord::Base
  
  before_save {self.email = email.downcase}
  
  validates(:name, 
            presence: true,
            length: {maximum: 50}
            )
  
  # regular expression for a robust valid email format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates(:email, 
            presence: true, 
            length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
            )
            
  validates(:password,
            length: {minimum: 6})

has_secure_password
            
end

SampleApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SampleApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

SampleApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def show
    @user = User.find(params[:id])
  end
end

SampleApp/app/helpers/application_helper.rb
module ApplicationHelper
  
  #returns full title on a per page basis
  def full_title(page_title = '')
    
    base_title = "Ruby on Rails Tutorial SampleApp"
    
    if page_title.empty?
      return base_title
    else
      return "#{page_title} | #{base_title}"
    end
  
  end
end

SampleApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

SampleApp/app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest("example@railstutorial.org".downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

SampleApp/app/views/layouts/_footer.html.erb
<!-- general footer element -->

<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact",  contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

SampleApp/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "SampleApp", root_path, class: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Login",  '#'  %></li>
        </ul>
      </nav>
    </div>
  </header>

SampleApp/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

SampleApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params)  %> <!--if Rails.env.development? -->
  </div>
</body>
</html>

SampleApp/app/views/static_pages/about.html.erb
<%provide(:title, "About")%>

<h1>About</h1>
    <p>
        This is the About page
    </p>

SampleApp/app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact')%>

<h1>Contact</h1>

<p>
  Contact the Ruby on Rails Tutorial about the sample app at the 
  <a href="http://railstutorial.org/#contact">Contact page</a>
</p>

SampleApp/app/views/static_pages/help.html.erb
<%provide(:title, "Help")%>

<h1>Help</h1>
    <p>
        This is the Help page
    </p>

SampleApp/app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1> Welcome to the SampleApp</h1>
    
    <h2>
        This is the home page for the
        <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample Application
    </h2>
    
    <%= link_to "Sign up Now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo missing"),
    'http://rubyonrails.org/' %>

SampleApp/app/views/users/new.html.erb
<%provide(:title,'SignUp')%>


<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

SampleApp/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1>
  <%= gravatar_for(@user) %>
  <%= @user.name %>
</h1>